[package]
name = "algor"
version = "0.1.0"
edition = "2021"
about = "Algor is a simple cli tool to explore rust algorithms"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }